import os
import json
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware

app = FastAPI(title="Linguistic Accommodation Simulation API")

# Configure CORS for local Next.js frontend requests
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # In production, specify the actual frontend origin
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

STATE_FILE = "simulation_state.json"
ANALYTICS_FILE = "analytics_results.json"

@app.get("/api/state")
def get_state():
    """Exposes the live simulation state JSON."""
    if not os.path.exists(STATE_FILE):
        # Look for run-specific state files as fallbacks
        run_states = [f for f in os.listdir(".") if f.startswith("state_") and f.endswith(".json")]
        if run_states:
            # Pick the most recently modified state file
            latest_state = max(run_states, key=os.path.getmtime)
            with open(latest_state, "r") as f:
                return json.load(f)
        raise HTTPException(status_code=404, detail="No simulation state file found.")
        
    with open(STATE_FILE, "r") as f:
        return json.load(f)

@app.get("/api/analytics")
def get_analytics():
    """Exposes the semantic evaluations JSON generated by the Gemini analytics script."""
    # Look for the analytics results file
    if not os.path.exists(ANALYTICS_FILE):
        # Check for run-specific state files to see if we can locate an analytics cache
        # If not, let's check for any analytics JSON cache
        run_analytics = [f for f in os.listdir(".") if f.startswith("analytics_") and f.endswith(".json")]
        if run_analytics:
            latest_analytics = max(run_analytics, key=os.path.getmtime)
            with open(latest_analytics, "r") as f:
                return json.load(f)
        raise HTTPException(status_code=404, detail="No analytics results file found. Please run analytics.py first.")
        
    with open(ANALYTICS_FILE, "r") as f:
        return json.load(f)

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="127.0.0.1", port=8000)
